In [1]:
%matplotlib inline
from keras.backend.tensorflow_backend import set_session
import tensorflow as tf
# set the memory usage
tf_config = tf.ConfigProto()
tf_config.gpu_options.allow_growth = True
set_session(tf.Session(config=tf_config))

import matplotlib.pyplot as plt
from scipy.io import loadmat
import numpy as np
import imp
import pandas as pd

Using TensorFlow backend.


In [2]:
import cwru 

window_size = 2048
data = cwru.CWRU(['12DriveEndFault'], ['1772'], window_size)
data.nclasses,data.classes,len(data.X_train),len(data.X_test)


Datasets/CWRU 12DriveEndFault 1772
0 Datasets/CWRU/NormalBaseline/1772/Normal.mat
(483903, 2)
1 Datasets/CWRU/12DriveEndFault/1772/0.007-Ball.mat
(121410, 2)
2 Datasets/CWRU/12DriveEndFault/1772/0.014-Ball.mat
(122136, 2)
3 Datasets/CWRU/12DriveEndFault/1772/0.021-Ball.mat
(121701, 2)
4 Datasets/CWRU/12DriveEndFault/1772/0.007-InnerRace.mat
(121991, 2)
5 Datasets/CWRU/12DriveEndFault/1772/0.014-InnerRace.mat
(121846, 2)
6 Datasets/CWRU/12DriveEndFault/1772/0.021-InnerRace.mat
(121556, 2)
7 Datasets/CWRU/12DriveEndFault/1772/0.007-OuterRace6.mat
(122426, 2)
8 Datasets/CWRU/12DriveEndFault/1772/0.014-OuterRace6.mat
(122136, 2)
9 Datasets/CWRU/12DriveEndFault/1772/0.021-OuterRace6.mat
(121991, 2)


(10,
 [('NormalBaselineNormal', 0),
  ('12DriveEndFault0.007-Ball', 1),
  ('12DriveEndFault0.014-Ball', 2),
  ('12DriveEndFault0.021-Ball', 3),
  ('12DriveEndFault0.007-InnerRace', 4),
  ('12DriveEndFault0.014-InnerRace', 5),
  ('12DriveEndFault0.021-InnerRace', 6),
  ('12DriveEndFault0.007-OuterRace6', 7),
  ('12DriveEndFault0.014-OuterRace6', 8),
  ('12DriveEndFault0.021-OuterRace6', 9)],
 6600,
 250)

In [3]:
from  preprocess import prepro
path = r'./Datasets/gearing'
train_X, train_Y, valid_X, valid_Y, test_X, test_Y = prepro(d_path=path,
                                                                length=2048,
                                                                number=4000,
                                                                normal=False,
                                                                rate=[0.1, 0.45, 0.45],
                                                                enc=False,
                                                                enc_step=28)


chip5a_x.npy
./Datasets/gearing/chip5a_x.npy
health_x.npy
./Datasets/gearing/health_x.npy
spall_x.npy
./Datasets/gearing/spall_x.npy
missing_x.npy
./Datasets/gearing/missing_x.npy
crack_x.npy
./Datasets/gearing/crack_x.npy


/usr/local/lib/python3.5/dist-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [4]:
import numpy as np
#==================================valid
print(valid_X.shape)
print(valid_Y)
gearing_valid_label = []
for i in range(len(valid_Y)):
    gearing_valid_label.append(np.argmax(valid_Y[i]))
print(gearing_valid_label[:100])
gearing_valid_classes = sorted(list(set(gearing_valid_label)))
print(gearing_valid_classes)
#==================================test
print(test_X.shape)
print(test_Y)
gearing_test_label = []
for i in range(len(test_X)):
    gearing_test_label.append(np.argmax(test_Y[i]))
print(gearing_test_label[:100])
gearing_test_classes = sorted(list(set(gearing_test_label)))
print(gearing_test_classes)

(9002, 2048)
[[0 1 0 0 0]
 [1 0 0 0 0]
 [0 1 0 0 0]
 ...
 [0 0 1 0 0]
 [0 0 0 0 1]
 [0 0 0 0 1]]
[1, 0, 1, 2, 3, 3, 4, 4, 4, 3, 3, 0, 2, 3, 0, 4, 2, 1, 1, 1, 1, 1, 2, 0, 0, 2, 0, 3, 4, 1, 2, 2, 3, 3, 0, 2, 4, 3, 1, 2, 1, 4, 3, 1, 0, 4, 3, 2, 4, 3, 2, 2, 0, 4, 1, 4, 3, 1, 4, 0, 3, 2, 0, 4, 4, 4, 4, 1, 0, 1, 4, 2, 3, 0, 0, 0, 1, 0, 3, 4, 3, 2, 1, 0, 2, 3, 3, 2, 1, 3, 3, 0, 3, 0, 2, 1, 2, 1, 3, 4]
[0, 1, 2, 3, 4]
(9003, 2048)
[[1 0 0 0 0]
 [0 0 0 0 1]
 [0 0 1 0 0]
 ...
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]]
[0, 4, 2, 0, 1, 2, 4, 2, 2, 3, 3, 4, 1, 4, 3, 1, 1, 1, 3, 1, 4, 1, 0, 1, 0, 1, 4, 4, 4, 0, 4, 0, 2, 0, 1, 3, 3, 4, 4, 2, 2, 1, 2, 1, 3, 3, 4, 3, 4, 2, 3, 2, 1, 1, 4, 4, 4, 0, 1, 1, 0, 3, 2, 4, 4, 2, 0, 0, 2, 2, 1, 0, 2, 4, 2, 1, 0, 1, 2, 0, 4, 4, 2, 1, 0, 1, 4, 0, 0, 1, 3, 1, 2, 2, 3, 0, 4, 0, 0, 1]
[0, 1, 2, 3, 4]


In [5]:
import models
siamese_net = models.load_siamese_net((window_size,1))
print('\nsiamese_net summary:')
siamese_net.summary()


siamese_net summary:
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            (None, 2048, 1)      0                                            
__________________________________________________________________________________________________
input_2 (InputLayer)            (None, 2048, 1)      0                                            
__________________________________________________________________________________________________
sequential_1 (Sequential)       (None, 100)          50772       input_1[0][0]                    
                                                                 input_2[0][0]                    
__________________________________________________________________________________________________
lambda_1 (Lambda)               (None, 100)          0           sequential_1[1][0]    

In [6]:
print('\nsequential_3 is WDCNN:')
siamese_net.layers[2].summary()


sequential_3 is WDCNN:
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_1 (Conv1D)            (None, 128, 16)           1040      
_________________________________________________________________
max_pooling1d_1 (MaxPooling1 (None, 64, 16)            0         
_________________________________________________________________
conv1d_2 (Conv1D)            (None, 64, 32)            1568      
_________________________________________________________________
max_pooling1d_2 (MaxPooling1 (None, 32, 32)            0         
_________________________________________________________________
conv1d_3 (Conv1D)            (None, 32, 64)            4160      
_________________________________________________________________
max_pooling1d_3 (MaxPooling1 (None, 16, 64)            0         
_________________________________________________________________
conv1d_4 (Conv1D)            (None, 16, 64)         

In [7]:
wdcnn_net = models.load_wdcnn_net()
print('\nwdcnn_net summary:')
wdcnn_net.summary()

51782

wdcnn_net summary:
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_3 (InputLayer)         (None, 2048, 1)           0         
_________________________________________________________________
sequential_2 (Sequential)    (None, 100)               50772     
_________________________________________________________________
dropout_2 (Dropout)          (None, 100)               0         
_________________________________________________________________
dense_4 (Dense)              (None, 10)                1010      
Total params: 51,782
Trainable params: 51,782
Non-trainable params: 0
_________________________________________________________________


In [8]:
import keras
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from keras.callbacks import ModelCheckpoint,EarlyStopping
from sklearn.metrics import confusion_matrix
import siamese
# imp.reload(siamese)
import utils
imp.reload(utils)

settings = {
  "N_way": 10,           # how many classes for testing one-shot tasks>
  "batch_size": 32,
  "best": -1,
  "evaluate_every": 600,   # interval for evaluating on one-shot tasks
  "loss_every": 20,      # interval for printing loss (iterations)
  "n_iter": 15000,
  "n_val": 2,          #how many one-shot tasks to validate on?
  "n": 0,
  "save_path":"",
  "save_weights_file": "weights-best-10-oneshot-low-data.hdf5"
}


exp_name = "EXP-C"
#exps = [90,6600]
exps = [90, 1000,  3000, 6600]
#exps =[6600]
see_rates = [0.7,0.8,0.9]
times = 10

In [ ]:
is_training = True    # enable or disable train models. if enable training, save best models will be update.
y_train_1 = []
# for i in range(len(data.y_train)):
def plot_confusion_matrix(cm, title,cmap):
        cm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]    # 归一化
        fig, ax = plt.subplots()
        im = ax.imshow(cm, interpolation='nearest', cmap=cmap)
        ax.figure.colorbar(im, ax=ax)
        # We want to show all ticks...
        #ax.set(xticks=np.arange(cm.shape[1]),yticks=np.arange(cm.shape[0]),xticklabels=labels_name, yticklabels=labels_name)
        ax.set(xticks=np.arange(cm.shape[1]),yticks=np.arange(cm.shape[0]))

        # Rotate the tick labels and set their alignment.
        plt.setp(ax.get_xticklabels(), rotation=45, ha="right",
                 rotation_mode="anchor")

        # Loop over data dimensions and create text annotations.
        fmt = '.2f'
        thresh = cm.max() / 2.
        for i in range(cm.shape[0]):
            for j in range(cm.shape[1]):
                ax.text(j, i, format(cm[i, j], fmt),
                        ha="center", va="center",
                        color="white" if cm[i, j] > thresh else "black")
        fig.tight_layout()
        return ax




#train_classes = sorted(list(set(data.y_train)))
train_classes = sorted(list(set(gearing_valid_label)))
#train_indices = [np.where(data.y_train[:][:][0] == i)[0] for i in train_classes]
train_indices = [np.where(gearing_valid_label[:][:][0] == i)[0] for i in train_classes]
for exp in exps:
    # enable the random seed for experimental reproduction
    np.random.seed(exp)
    scores_1_shot = []
    scores_5_shot = []
    num = int(exp/len(train_classes))
    settings['evaluate_every'] = 300 if exp<1000 else 600
    #print(settings['evaluate_every'])
    for time_idx in range(times):
#         np.random.seed(0)
#         train_idxs = []
#         val_idxs = []
#         for i, c in enumerate(train_classes):
#             select_idx = train_indices[i][np.random.choice(len(train_indices[i]), num, replace=False)]
#             split = int(0.6*num)
#             train_idxs.extend(select_idx[:split])
#             end = num
#             if(0.4*num>100):
#                 end = split+100
#             val_idxs.extend(select_idx[split:end])
        #==========================================================
        #X_train, y_train = data.X_train[:,:,0],data.y_train
        #X_train, y_train = data.X_train[:exp,:,0],data.y_train[:exp]
#         print(valid_X.shape)
#         print(gearing_valid_label.shape)
        X_train, y_train = valid_X[:exp,:],gearing_valid_label[:exp]
        #===============================================================
        #print(X_train.shape)
        #print("=================X_train,y_train===================")
        X_train = X_train.reshape(len(X_train),2048,1)
        #print(X_train.shape, y_train.shape)
        #print(X_train, y_train)
        X_val, y_val = test_X,gearing_test_classes
        #print("=================X_val,y_val===================")
        #print(X_val, y_val)
#         print(train_idxs[0:10])
#         print(val_idxs[0:10])   
            
#         random_train_classes = [0]+list(np.random.choice(list(range(1,10)), 9, replace=False))
    
        print("\n%s-%s"%(exp,time_idx) + '*'*80)
        settings["save_path"] = "tmp/%s/size_%s/time_%s/" % (exp_name,exp,time_idx)
        #print(settings["save_path"])
        data._mkdir(settings["save_path"])
        #random_select_classes = random_train_classes[:int(rate*len(train_classes))]
        #print(random_select_classes)
#         train_idxs_rate = np.array([np.where(y_train == i)[0] for i in train_classes]).reshape(-1)
#         print(train_idxs_rate)
#         val_idxs_rate =  np.array([np.where(y_val == i)[0] for i in gearing_test_classes]).reshape(-1)
#         print(val_idxs_rate)
#         X_train_rate, y_train_rate = X_train[train_idxs_rate],y_train[train_idxs_rate]
#         print(X_train_rate, y_train_rate)
#         print("===============================")
#         X_val_rate  = X_val[val_idxs_rate]
#         print(val_idxs_rate)
#         y_val_rate = y_val[val_idxs_rate]
#         print(X_val_rate, y_val_rate)
#         print("=================X_train_rate.shape=================")
#         print(X_train_rate.shape)
#         print(y_train_rate)
#         print("=================X_val_rate.shape=================")
#         print(X_val_rate.shape)
#         print(y_val_rate)
#         # load one-shot model and training
        #print(X_train.shape)
        test_X_train, test_y_train = data.X_train[:,:,0],data.y_train
        print(len(test_X_train))
        siamese_net = models.load_siamese_net()
        siamese_loader = siamese.Siamese_Loader(X_train,
                                        y_train,
                                        test_X_train,
                                        test_y_train)

        if(is_training):
            print(siamese.train_and_test_oneshot(settings,siamese_net,siamese_loader))

        print("load best weights",settings["save_path"] + settings['save_weights_file'])
        siamese_net.load_weights(settings["save_path"] + settings['save_weights_file'])
        
        
        siamese_loader = siamese.Siamese_Loader(valid_X,
                                        gearing_valid_label,
                                        test_X_train,
                                        test_y_train)
        s = 'val'
        preds_5_shot = []
        scores = []
        for k in range(5):
#             print(len(siamese_loader.classes[s]))
#             print(len(siamese_loader.data[s]))
            #val_acc,preds,c = siamese_loader.test_oneshot2(siamese_net,5,9003,verbose=False)
            val_acc,preds,c = siamese_loader.test_oneshot2(siamese_net,len(siamese_loader.classes[s]),len(siamese_loader.data[s]),verbose=False)
#             confusion_plot(preds[:,1],preds[:,0])
#             print(preds[:,1])
#             print(preds[:,1].shape)
            
#             print(data.y_train)
#             print(data.y_train.shape)
            C = confusion_matrix(preds[:,1],data.y_train)
            #labels_name=["Normal","Outter","Inner","Ball"]
            np.set_printoptions(precision=2)
            plot_confusion_matrix(C,  "HAR Confusion Matrix",plt.cm.Blues)
            plt.savefig('./Confusion_matrix_gearing2bearing/'+str(exp)+'_'+str(time_idx)+'_'+str(k)+'.png')
            plt.show()
            
            
            print(val_acc)
            scores.append(val_acc)
            preds_5_shot.append(preds[:,1])
        preds = []
        for line in np.array(preds_5_shot).T:
            preds.append(np.argmax(np.bincount(line)))
#         confusion_plot(np.array(preds),data.y_test) 
        #print(len(gearing_test_label))
        #print(len(np.array(preds)))
        score_5_shot = accuracy_score(test_y_train,np.array(preds))*100
        print('==============================plot_confusion_matrix_score_5_shot=========================================')
        C = confusion_matrix(np.array(preds),test_y_train)
        #labels_name=["Normal","Outter","Inner","Ball"]
        np.set_printoptions(precision=2)
        plot_confusion_matrix(C,  "HAR Confusion Matrix",plt.cm.Blues)
        plt.savefig('./Confusion_matrix_gearing2bearing/score_5_shot_'+str(exp)+'_'+str(time_idx)+'_'+str(k)+'.png')
        plt.show()
        print('5_shot:',score_5_shot)
        scores_1_shot.append(scores[0])
        scores_5_shot.append(score_5_shot)
    print(scores_1_shot)
    print(scores_5_shot)
    #a =pd.DataFrame(np.array(scores_1_shot).reshape(-1,len(see_rates)))
    a =pd.DataFrame(np.array(scores_1_shot))
    a.columns = ["gearing,9003"]
    a.to_csv("tmp/%s/size_%s/scores_1_shot.csv" % (exp_name,exp),index=True)


    #a =pd.DataFrame(np.array(scores_5_shot).reshape(-1,len(see_rates)))
    a =pd.DataFrame(np.array(scores_5_shot))
    a.columns = ["gearing,9003"]
    a.to_csv("tmp/%s/size_%s/scores_5_shot.csv" % (exp_name,exp),index=True)

In [ ]:
exps = [90, 6600]
#exps = [90,500,1000,2000,3000,6600]
scores_1_shot_all = pd.DataFrame()
scores_5_shot_all = pd.DataFrame()

for exp in exps:
    file_path = "tmp/%s/size_%s" % (exp_name,exp)
    print(file_path)
    tmp_data = pd.read_csv("%s/scores_1_shot.csv" % (file_path), 
                           sep=',', index_col=0)
    print(tmp_data)
    #tmp_data = pd.DataFrame(tmp_data.values.reshape(-1,len(see_rates)))
#     tmp_data = pd.DataFrame(tmp_data.values.reshape(-1,50))
#     tmp_data.columns = [len(gearing_valid_label)]
#     tmp_data['model'] = 'One-shot'
#     tmp_data['exp'] = exp 
#     scores_1_shot_all = pd.concat([scores_1_shot_all,tmp_data],axis=0)

    tmp_data = pd.read_csv("%s/scores_5_shot.csv" % (file_path), 
                           sep=',', index_col=0)
    print(tmp_data)
    #tmp_data = pd.DataFrame(tmp_data.values.reshape(-1,len(see_rates)))
#     tmp_data = pd.DataFrame(tmp_data.values.reshape(-1,50))
#     tmp_data.columns = [len(gearing_valid_label)]
#     tmp_data['model'] = 'Five-shot'
#     tmp_data['exp'] = exp 
#     scores_5_shot_all = pd.concat([scores_5_shot_all,tmp_data],axis=0)


scores_1_shot_all.to_csv("tmp/%s/scores_1_shot_all.csv" % (exp_name), float_format='%.6f', index=True)
scores_5_shot_all.to_csv("tmp/%s/scores_5_shot_all.csv" % (exp_name), float_format='%.6f', index=True)

scores_1_shot_all['model'] = 'One-shot'
scores_5_shot_all['model'] = 'Five-shot'

scores_all = pd.concat([scores_1_shot_all,scores_5_shot_all],axis=0)
scores_all.to_csv("tmp/%s/scores_all.csv" % (exp_name), float_format='%.6f', index=True)   

scores_all